// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.

namespace u
{
    [default_interface]
    runtimeclass AboutPage : Microsoft.UI.Xaml.Controls.Page
    {
        AboutPage();
        Int32 MyProperty;
    }
}
